site_name: Getting Started
site_favicon: favicon.ico
pages:
- Getting Started: index.md
- TVOS SDK: tvOsSdk.md
- ANDROID TV / FIRE TV SDK: androidTVSDK.md
- ROKU: rokuSdk.md
- WEB: webSDK.md
- UNITY ANDROID TV / FIRE TV: unityAndroidTV.md
- UNITY TVOS: unityTVOS.md
theme_dir: '../mkdocs-material/material'
markdown_extensions:
  - codehilite(css_class=code)
  - admonition
extra:
  author:
    github: color-tv
